baseURL = 'http://example.org/'
title = 'MorphWiz 2 Operation Manual'
languageCode = 'en-us'
theme = ["hugo-book"]

[params]
  dateform = "Jan 2, 2006"
  dateformShort = "Jan 2"
  dateformNum = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  
  BookTheme = 'auto'
  BookToC = false
  BookComments = false
  BookSection = 'docs'
  BookSearch = true
  BookPortableLinks = true
  BookMenuBundle = '/menu'